spring:
  application:
    name: 'cliente'
  datasource:
    username: root 
    password: 123456
    url: jdbc:mysql://localhost:3306/cliente
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
  servlet:
    context-path: /cliente
  